services:
  redisCache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass cCf75SWA8UTxzx1kT1V6O4RX5ynZo6
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local